/* eslint-disable react-refresh/only-export-components */
export * from "./about";
export * from "./education";
export * from "./footer";
export * from "./hero";
export * from "./navbar";
export * from "./parallax";
export * from "./pastimes";
export * from "./projects";
export * from "./typing";
export * from "./work-experience";
